SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS
  contract_settlements,
  contract_service_fees,
  position_conditions,
  contract_positions,
  contracts,
  deliveries,
  contract_costs,
  article_reservations,
  audit_log,
  _import_errors,
  fakturownia_products_cache,
  fakturownia_settings,
  fee_preset_groups,
  service_fee_templates,
  service_fee_template_items,
  salespeople,
  branches,
  rate_types,
  postal_codes,
  contractor_addresses,
  contractors,
  articles,
  categories,
  company,
  users,
  article_rate_presets,
  article_rate_preset_items;
SET FOREIGN_KEY_CHECKS=1;
